{"fullName": "testCases.test_login.TestLogin#test_login_00_failure", "historyId": "f21195535820a35ce97f544419a4fcdc", "labels": [{"name": "story", "value": "异常登录测试"}, {"name": "feature", "value": "测试登录功能"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "suite", "value": "test_login"}, {"name": "parentSuite", "value": "testCases"}, {"name": "host", "value": "DESKTOP-6IIPB06"}, {"name": "thread", "value": "8932-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}], "parameters": [{"name": "invalid_datas", "value": "{'pwd': '', 'username': 'admin', 'exp': '登录失败'}"}], "status": "passed", "name": "test_login_00_failure[invalid_datas1]", "start": 1630548592655, "attachments": [{"type": "text/plain", "source": "f2cb025a-589d-4581-80f5-ff81099e56a7-attachment.txt", "name": "log"}], "stop": 1630548592898, "testCaseId": "2560b1f5fa20bb64c3ef64234187c151", "uuid": "5e4ead9d-f4a4-4552-a9d3-49ce6ce0361e"}