{"fullName": "testCases.test_login.TestLogin#test_login_00_failure", "historyId": "e8a9eb4eb6179b9e365715481540f53e", "labels": [{"name": "story", "value": "异常登录测试"}, {"name": "feature", "value": "测试登录功能"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "suite", "value": "test_login"}, {"name": "parentSuite", "value": "testCases"}, {"name": "host", "value": "DESKTOP-6IIPB06"}, {"name": "thread", "value": "8932-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}], "parameters": [{"name": "invalid_datas", "value": "{'pwd': 'admin@123456', 'username': '', 'exp': '登录失败'}"}], "status": "passed", "name": "test_login_00_failure[invalid_datas2]", "start": 1630548593277, "attachments": [{"type": "text/plain", "source": "f6455366-edcd-40ff-9f12-4c047ab2d88a-attachment.txt", "name": "log"}], "stop": 1630548593552, "testCaseId": "2560b1f5fa20bb64c3ef64234187c151", "uuid": "a90ef7ab-e068-4393-b23a-eec77e3b7f5b"}