{"fullName": "testCases.test_login.TestLogin#test_login_00_failure", "historyId": "9291a8d0ca7daaeed9cba58fe03af9f0", "labels": [{"name": "story", "value": "异常登录测试"}, {"name": "feature", "value": "测试登录功能"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "suite", "value": "test_login"}, {"name": "parentSuite", "value": "testCases"}, {"name": "host", "value": "DESKTOP-6IIPB06"}, {"name": "thread", "value": "8932-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}], "parameters": [{"name": "invalid_datas", "value": "{'pwd': 'admin', 'username': 'admin', 'exp': '登录失败'}"}], "status": "passed", "name": "test_login_00_failure[invalid_datas3]", "start": 1630548593907, "attachments": [{"type": "text/plain", "source": "ec3694c5-e294-4867-bf9e-0c445f8e259e-attachment.txt", "name": "log"}], "stop": 1630548594191, "testCaseId": "2560b1f5fa20bb64c3ef64234187c151", "uuid": "f52e73ad-0247-48e0-ad2d-153683e40a9a"}